package NewSolution.a_model;

/*Generated by MPS */

import java.net.URL;
import java.net.URLConnection;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.MalformedURLException;
import java.io.IOException;

public class map_Definition {
  public static void main(String[] args) {
    try {
      URL url = new URL("http://www.google.com");
      URLConnection con = url.openConnection();
      con.setConnectTimeout(5000);
      BufferedReader reader = new BufferedReader(new InputStreamReader(con.getInputStream()), 10000);
      System.out.println(reader.readLine());
    } catch (MalformedURLException e) {
    } catch (IOException e) {
    }
  }
}
